name: ğŸ³ Docker Images [main]

on:
  push:
    branches:
      - main
      - dev

jobs:
  windows-build-and-push:
    name: ğŸ–¼ï¸ Windows Docker Build and Push
    runs-on: windows-latest
    
    steps:
      - name: ğŸ” Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸ–¥ï¸ Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: ğŸ·ï¸ Fetch Commit SHA
        id: get_sha
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"
        
      - name: ğŸ·ï¸ Extract Branch Name
        id: get_branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
        
      - name: ğŸ› ï¸ Build and Push Docker Images
        run: |
          docker build -t dublok/statsniper:windows-${{ steps.get_branch.outputs.branch }} -f ./src/Dockerfile.windows ./src
          docker push dublok/statsniper:windows-${{ steps.get_branch.outputs.branch }}
          docker tag dublok/statsniper:windows-${{ steps.get_branch.outputs.branch }} dublok/statsniper:win-${{ steps.get_branch.outputs.branch }} dublok/statsniper:windows-${{ steps.get_branch.outputs.branch }}-${{ steps.get_sha.outputs.sha }}
          docker push dublok/statsniper:windows-${{ steps.get_branch.outputs.branch }}-${{ steps.get_sha.outputs.sha }}

  linux-build-and-push:
    name: ğŸ§ Linux Docker Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ” Checkout Repository
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: ğŸ› ï¸ Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ–¥ï¸ Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: ğŸ·ï¸ Fetch Commit SHA
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: ğŸ·ï¸ Extract Branch Name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: ğŸ› ï¸ Build and Push Docker Images
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./src
          file: ./src/Dockerfile.linux
          push: true
          platforms: linux/amd64,linux/arm64,linux/s390x
          tags: |
            dublok/statsniper:main
            dublok/statsniper:linux-${{ github.ref_name }}
            dublok/statsniper:linux-${{ github.ref_name }}-${{ env.SHA_SHORT }}

