name: ğŸ³ Windows Docker Image [main]

on: 
  push:
    branches:
      - main

jobs:
  # ğŸ‘·â€â™‚ï¸ Job to build and push the Windows Docker image
  build-and-push:
    runs-on: windows-latest
    
    steps:
      # ğŸ›ï¸ Step 1: Checkout the repository to access its files
      - name: ğŸ” Checkout Repository
        uses: actions/checkout@v4

      # ğŸ›ï¸ Step 2: Login to DockerHub to push the Docker image
      - name: ğŸ–¥ï¸ Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # ğŸ›ï¸ Step 3: Get the Commit SHA from the GitHub SCM
      - name: ğŸ·ï¸ Fetch Commit SHA
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # ğŸ›ï¸ Step 4: Build and push the Windows Docker image to DockerHub
      - name: ğŸ› ï¸ Build and Push Docker Images
        run: |
          docker build -t dublok/statsniper:windows-main -f ./src/Dockerfile.windows ./src
          docker push dublok/statsniper:windows-main
          docker tag dublok/statsniper:windows-main dublok/statsniper:windows-main-${{ env.SHA_SHORT }}
          docker push dublok/statsniper:windows-main-${{ env.SHA_SHORT }}