name: ğŸ³ Windows Docker Image [main]

on: 
  push:
    branches:
      - main

jobs:
  # ğŸ‘·â€â™‚ï¸ Job to build and push the Windows Docker image
  build-and-push:
    runs-on: windows-latest
    
    steps:
      # ğŸ›ï¸ Step 1: Checkout the repository to access its files
      - name: ğŸ” Checkout Repository
        uses: actions/checkout@v4

      # ğŸ›ï¸ Step 2: Set up Docker Buildx for building the Windows Docker images
      - name: ğŸ› ï¸ Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ğŸ›ï¸ Step 3: Login to DockerHub to push the Docker image
      - name: ğŸ–¥ï¸ Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # ğŸ›ï¸ Step 4: Get the tag name from the GitHub reference
      - name: ğŸ·ï¸ Fetch Tag Name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      # ğŸ›ï¸ Step 5: Build and push the Windows Docker image to DockerHub
      - name: ğŸ› ï¸ Build and Push Docker Images
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./src
          file: ./Dockerfile.windows
          push: true
          platforms: windows/amd64
          tags: dublok/statsniper:windows-latest,dublok/statsniper:windows-${{ env.TAG }}
