name: ğŸ³ Linux Docker Image [latest]

# This workflow is triggered when a release is published
on: 
  release:
    types: [published]

jobs:
  # ğŸ‘·â€â™‚ï¸ Job to build and push the Docker image
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      # ğŸ›ï¸ Step 1: Checkout the repository to access its files
      - name: ğŸ” Checkout Repository
        uses: actions/checkout@v4

      # ğŸ›ï¸ Step 2: Set up QEMU for cross-platform build
      - name: ğŸ› ï¸ Setup QEMU
        uses: docker/setup-qemu-action@v3

      # ğŸ›ï¸ Step 3: Set up Docker Buildx for building the Docker images
      - name: ğŸ› ï¸ Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ğŸ›ï¸ Step 4: Login to DockerHub to push the Docker image
      - name: ğŸ–¥ï¸ Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # ğŸ›ï¸ Step 5: Get the tag name from the GitHub reference
      - name: ğŸ·ï¸ Fetch Tag Name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      # ğŸ›ï¸ Step 6: Build and push the Docker image to DockerHub
      - name: ğŸ› ï¸ Build and Push Docker Images
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./src
          file: ./Dockerfile.linux
          push: true
          platforms: linux/amd64,linux/arm64,linux/s390x
          tags: dublok/statsniper:linux-latest,dublok/statsniper:linux-${{ env.TAG }}
